# Generated by Django 4.2 on 2023-06-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название сферы деятельности', max_length=128, verbose_name='Название сферы деятельности')),
                ('slug', models.SlugField(help_text='Введите Slug сферы деятельности', max_length=200, unique=True, verbose_name='Slug сферы деятельности')),
            ],
            options={
                'verbose_name': 'Сфера деятельности',
                'verbose_name_plural': 'Сферы деятельности',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название организации на Русском языке. Не более 128 символов', max_length=128, verbose_name='Название организации на Русском языке')),
                ('name_eng', models.CharField(help_text='Введите название организации на Английском языке. Не более 128 символов', max_length=128, verbose_name='Название организации на Английском языке')),
                ('short_description', models.TextField(help_text='Введите короткое описание организации. Не более 256 символов', max_length=256, verbose_name='Короткое описание')),
                ('url_site', models.URLField(help_text='Введите ссылку на корпоративный сайт', verbose_name='Ссылка на корпоративный сайт')),
                ('url_vacancies', models.URLField(blank=True, help_text='Введите ссылку на вакансии', verbose_name='Ссылка на вакансии')),
                ('url_internships', models.URLField(blank=True, help_text='Введите ссылку на стажировки', verbose_name='Ссылка на стажировки')),
                ('url_tg_company', models.URLField(blank=True, help_text='Введите ссылку на Telegram организации', verbose_name='Ссылка на Telegram организации')),
                ('url_tg_vacancies', models.URLField(blank=True, help_text='Введите ссылку на Telegram вакансий организации', verbose_name='Ссылка на Telegram вакансий организации')),
                ('url_tg_internships', models.URLField(blank=True, help_text='Введите ссылку на Telegram всех стажировок компании', verbose_name='Ссылка на Telegram всех стажировок компании')),
                ('logo', models.FileField(blank=True, help_text='Выберите файл для загрузки логотипа организации', upload_to='company_logo/', verbose_name='Логотип организации')),
                ('slug', models.SlugField(help_text='Введите slug организации', max_length=200, unique=True, verbose_name='Slug организации')),
                ('size', models.CharField(blank=True, choices=[('indie', 'Инди-компания'), ('little', 'Маленькая компания'), ('small', 'Небольшая компания'), ('medium', 'Средняя компания'), ('big', 'Крупная компания'), ('giant', 'Крупнейшая компания')], help_text='Выберите размер организации', max_length=10, verbose_name='Размер организации')),
                ('areas', models.ManyToManyField(help_text='Выберите сферу деятельности организации', related_name='companies', to='internships.area', verbose_name='Сфера деятельности организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='InternshipField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите наименование направления стажировки', max_length=128, verbose_name='Название направления стажировки')),
                ('slug', models.SlugField(help_text='Введите Slug направления стажировки', max_length=200, unique=True, verbose_name='Slug направления стажировки')),
            ],
            options={
                'verbose_name': 'Направление стажировки',
                'verbose_name_plural': 'Направления стажировки',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите наименование стажировки. Не более 128 символов.', max_length=128, verbose_name='Название стажировки')),
                ('short_description', models.TextField(help_text='Введите короткое описание стажировки. Не более 256 символов.', max_length=256, verbose_name='Короткое описание')),
                ('start_date', models.DateField(verbose_name='Старт подачи заявок')),
                ('end_date', models.DateField(verbose_name='Окончание приёма')),
                ('is_permanent', models.BooleanField(default=False, verbose_name='Набор на стажировку ведётся постоянно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания стажировки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления стажировки')),
                ('published_at', models.DateTimeField(auto_now=True, verbose_name='Дата публикации стажировки')),
                ('visibility', models.BooleanField(default=False, verbose_name='Стажировка опубликована')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='internships.company', verbose_name='Организация')),
                ('fields', models.ManyToManyField(related_name='internships', to='internships.internshipfield', verbose_name='Направление стажировки')),
            ],
            options={
                'verbose_name': 'Стажировка',
                'verbose_name_plural': 'Стажировки',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='internship',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique_internship_for_company'),
        ),
    ]
