# Generated by Django 4.2 on 2023-05-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите наименование стажировки', max_length=128, verbose_name='Направление стажировки')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug направления стажировки')),
            ],
            options={
                'verbose_name': 'Направление стажировки',
                'verbose_name_plural': 'Направления стажировки',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите наименование стажировки. Не более 128 символов.', max_length=128, verbose_name='Название стажировки')),
                ('short_description', models.TextField(help_text='Введите короткое описание стажировки. Не более 256 символов.', max_length=256, verbose_name='Короткое описание')),
                ('start_date', models.DateField(verbose_name='Старт подачи заявок')),
                ('end_date', models.DateField(verbose_name='Окончание приёма')),
                ('is_permanent', models.BooleanField(verbose_name='Набор на стажировку ведётся постоянно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания стажировки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления стажировки')),
                ('published_at', models.DateTimeField(auto_now=True, verbose_name='Дата публикации стажировки')),
                ('visibility', models.BooleanField(verbose_name='Стажировка опубликована')),
                ('fields', models.ManyToManyField(related_name='internships', to='internships.internshipfield', verbose_name='Направление стажировки')),
            ],
            options={
                'verbose_name': 'Стажировка',
                'verbose_name_plural': 'Стажировки',
                'ordering': ('-updated_at',),
            },
        ),
    ]
