# Generated by Django 4.2 on 2023-06-17 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(help_text='Выберите организацию', on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='internships.company', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='end_date',
            field=models.DateField(help_text='Введите дату окончания подачи заявок', verbose_name='Окончание приёма заявок'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='fields',
            field=models.ManyToManyField(help_text='Выберите направление стажировки', related_name='internships', to='internships.internshipfield', verbose_name='Направление стажировки'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='is_permanent',
            field=models.BooleanField(default=False, help_text='Выберите для постоянного набора на стажировку', verbose_name='Набор на стажировку ведётся постоянно'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='name',
            field=models.CharField(db_index=True, help_text='Введите наименование стажировки. Не более 128 символов', max_length=128, verbose_name='Название стажировки'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='short_description',
            field=models.TextField(help_text='Введите короткое описание стажировки. Не более 256 символов', max_length=256, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='start_date',
            field=models.DateField(help_text='Введите дату начала подачи заявок', verbose_name='Начало подачи заявок'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='visibility',
            field=models.BooleanField(default=False, help_text='Выберите для публикации стажировки', verbose_name='Стажировка опубликована'),
        ),
    ]
