# Generated by Django 4.2 on 2023-06-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipfield',
            name='name',
            field=models.CharField(db_index=True, help_text='Введите наименование стажировки', max_length=128, verbose_name='Название направления стажировки'),
        ),
    ]
